package com.ixe.persist;

import org.bson.Document;

import java.time.Instant;

public class FileSummary {

    private String filePath;                            // path on the source system.

    private String machineId;                           // unique identifier for a machine generated by the
                                                        // currently running IndexEverywhere agent.

    private Instant summaryGenerationTime;              // time at which the summary was generated for a file

    private String fileType;                            // file extension

    private String indexableText;                       // indexable metadata as text to drop into Solr

    private Document richMetadata;                      // richly structured metadata to be read into MongoDB
                                                        // may expose to power users
}
